# Generated by Django 5.1.7 on 2025-04-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0002_alter_documento_archivo_alter_notificacion_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
