# Generated by Django 5.1.7 on 2025-05-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0003_alter_documento_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
